version: 2
sources:
  - name: gz_raw
    schema: gz_raw_data
    description: "First dbt model"
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales
        columns:
          - name: date_date
            description: sales of greenweeze
      - name: product
        identifier: raw_gz_product
        description: product
        columns:
          - name: products_id
            description: id of products
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship
        columns:
          - name: orders_id
            description: id of orders
            tests:
              - unique
              - not_null
